# Generated by Django 3.2.7 on 2021-09-18 11:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Python'), (2, 'C++'), (3, 'C#'), (4, 'Javascript'), (5, 'Java'), (6, 'Html'), (7, 'Css'), (5, 'Django'), (5, 'React')], max_length=4, null=True),
        ),
    ]
