# Generated by Django 3.2.7 on 2021-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=14626423423, max_length=255, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
