# Generated by Django 3.2.7 on 2021-09-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('comment', models.CharField(max_length=255, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': "Contact's",
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('client', models.CharField(max_length=255, verbose_name='client')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('skills', models.CharField(max_length=255, verbose_name='skills')),
                ('link', models.URLField(max_length=255, verbose_name='link')),
                ('comment', models.CharField(max_length=255, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': "Scheme's",
            },
        ),
    ]
