# Generated by Django 3.2.7 on 2021-09-18 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='linkedin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
